// <auto-generated />
using System;
using BasketbolAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BasketbolAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515182657_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BasketbolAPI.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("int");

                    b.Property<int>("HomeScore")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("Matches");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AwayScore = 82,
                            AwayTeamId = 2,
                            HomeScore = 78,
                            HomeTeamId = 1,
                            MatchDate = new DateTime(2024, 10, 17, 20, 45, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AwayScore = 76,
                            AwayTeamId = 1,
                            HomeScore = 91,
                            HomeTeamId = 2,
                            MatchDate = new DateTime(2025, 1, 3, 19, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AwayScore = 88,
                            AwayTeamId = 3,
                            HomeScore = 71,
                            HomeTeamId = 1,
                            MatchDate = new DateTime(2024, 11, 8, 18, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            AwayScore = 83,
                            AwayTeamId = 4,
                            HomeScore = 97,
                            HomeTeamId = 3,
                            MatchDate = new DateTime(2024, 12, 20, 20, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            AwayScore = 90,
                            AwayTeamId = 4,
                            HomeScore = 86,
                            HomeTeamId = 2,
                            MatchDate = new DateTime(2025, 2, 6, 20, 30, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            AwayScore = 79,
                            AwayTeamId = 5,
                            HomeScore = 82,
                            HomeTeamId = 1,
                            MatchDate = new DateTime(2024, 12, 28, 19, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("BasketbolAPI.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("JerseyNumber")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Sadık Emir Kabaca",
                            JerseyNumber = 11,
                            Position = "Forvet",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            FullName = "David McCormack",
                            JerseyNumber = 5,
                            Position = "Pivot",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 3,
                            FullName = "James Palmer Jr.",
                            JerseyNumber = 0,
                            Position = "Şutör gard",
                            TeamId = 1
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Kostas Sloukas",
                            JerseyNumber = 10,
                            Position = "Oyun kurucu",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Mathias Lessort",
                            JerseyNumber = 26,
                            Position = "Pivot",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 6,
                            FullName = "Juancho Hernangómez",
                            JerseyNumber = 41,
                            Position = "Forvet",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 7,
                            FullName = "Kostas Antetokounmpo",
                            JerseyNumber = 37,
                            Position = "Forvet",
                            TeamId = 2
                        },
                        new
                        {
                            Id = 8,
                            FullName = "Nikola Kalinić",
                            JerseyNumber = 12,
                            Position = "Forvet",
                            TeamId = 3
                        },
                        new
                        {
                            Id = 9,
                            FullName = "Sergio Llull",
                            JerseyNumber = 23,
                            Position = "Şutör gard",
                            TeamId = 4
                        },
                        new
                        {
                            Id = 10,
                            FullName = "Nigel Hayes-Davis",
                            JerseyNumber = 11,
                            Position = "Forvet",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 11,
                            FullName = "Nick Calathes",
                            JerseyNumber = 33,
                            Position = "Oyun kurucu",
                            TeamId = 5
                        },
                        new
                        {
                            Id = 12,
                            FullName = "Tyler Dorsey",
                            JerseyNumber = 22,
                            Position = "Şutör gard",
                            TeamId = 5
                        });
                });

            modelBuilder.Entity("BasketbolAPI.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Coach")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FoundedYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Istanbul",
                            Coach = "Jurij Zdovc",
                            FoundedYear = 1911,
                            Name = "Galatasaray"
                        },
                        new
                        {
                            Id = 2,
                            City = "Athens",
                            Coach = "Ergin Ataman",
                            FoundedYear = 1919,
                            Name = "Panathinaikos"
                        },
                        new
                        {
                            Id = 3,
                            City = "Barcelona",
                            Coach = "Roger Grimau",
                            FoundedYear = 1923,
                            Name = "FC Barcelona"
                        },
                        new
                        {
                            Id = 4,
                            City = "Madrid",
                            Coach = "Chus Mateo",
                            FoundedYear = 1931,
                            Name = "Real Madrid"
                        },
                        new
                        {
                            Id = 5,
                            City = "Istanbul",
                            Coach = "Sarunas Jasikevicius",
                            FoundedYear = 1913,
                            Name = "Fenerbahçe Beko"
                        });
                });

            modelBuilder.Entity("BasketbolAPI.Models.Match", b =>
                {
                    b.HasOne("BasketbolAPI.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BasketbolAPI.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BasketbolAPI.Models.Player", b =>
                {
                    b.HasOne("BasketbolAPI.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
